version: '3'
services:
 etcd:
  image: bitnami/etcd
  networks:
   - inet1
  ports:
   - 2379:2379
   - 2380:2380
  environment:
   - ALLOW_NONE_AUTHENTICATION=yes
   - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
  deploy:
   replicas: 1

networks:
 inet1:
  external:
   name: rabbitmq-network
